# Generated by Django 4.2.1 on 2023-06-03 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resume',
            options={'verbose_name_plural': 'resumes'},
        ),
    ]
